(function(){
    var modules={
        "panel-main":    	        {url:"$H/m/panel-main.html",router:1},
        "panel-child":              {url:"$H/m/panel-child.html"},
        
        "participant-data":   		        {url:"$H/m/participant/participant-data.html",Table:"participant-schizophrenia",form_module:"participant-form",router:1,
                                                child_panel:"panel-child",
                                                questionnaire_setup:"online-questionnaire-setup",
                                                online_questionnaire:"online-questionnaire-app",
                                                participant_id:{field1:"Subject_ID",field2:"Subject_Initials"},
                                                participant_export:"ID,Subject_ID,Screening_Number,Randomisation_Number,Subject_Initials,Gender,DOB"
                                            },
        "participant-form":   		        {url:"$H/m/participant/participant-form.html",Table:"participant-schizophrenia"},

        "online-questionnaire-setup":       {url:"$H/m/oq-setup.html",Table:"participant-schizophrenia"},
        "online-questionnaire-app":         {url:"$H/oq.html"},

        "notes-data":  	                    {url:"$H/m/library/notes-data.html",Table:"notes-schizophrenia",form_module:"notes-form",router:1},
        "notes-form":  	                    {url:"$H/m/library/notes-form.html",Table:"notes-schizophrenia"},

        "randomisation-table-data-schizophrenia":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-schizophrenia",form_module:"randomisation-table-form-schizophrenia"},
        "randomisation-table-form-schizophrenia":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-schizophrenia"},

        "adverse-event-data-schizophrenia":             {url:"$H/m/library/adverse-event-data.html",Table:"adverse-event-schizophrenia",form_module:"adverse-event-form-schizophrenia",task_name:"Adverse Event"},
        "adverse-event-form-schizophrenia":             {url:"$H/m/library/adverse-event-form.html",Table:"adverse-event-schizophrenia",task_name:"Adverse Event"},
        "file-notes-data-schizophrenia":                {url:"$H/m/library/file-notes-data.html",Table:"file-notes-schizophrenia",form_module:"file-notes-form-schizophrenia",task_name:"File Notes"},
        "file-notes-form-schizophrenia":                {url:"$H/m/library/file-notes-form.html",Table:"file-notes-schizophrenia",task_name:"File Notes"},
        "protocol-amendments-data-schizophrenia":       {url:"$H/m/library/upload-file-data.html",Table:"protocol-amendments-schizophrenia",form_module:"protocol-amendments-form-schizophrenia",task_name:"Protocol Amendments"},
        "protocol-amendments-form-schizophrenia":       {url:"$H/m/library/upload-file-form.html",Table:"protocol-amendments-schizophrenia",task_name:"Protocol Amendments"},
        
        "s-visit-date-data-schizophrenia":              {url:"$H/m/library/date-data.html",Table:"s-visit-date-schizophrenia",form_module:"s-visit-date-form-schizophrenia",task_name:"Visit Date"},
        "s-visit-date-form-schizophrenia":              {url:"$H/m/library/date-form.html",Table:"s-visit-date-schizophrenia",task_name:"Visit Date"},
        "s-anthropometry-data-schizophrenia":           {url:"$H/m/library/anthropometry-data.html",Table:"s-anthropometry-schizophrenia",form_module:"s-anthropometry-form-schizophrenia",task_name:"Anthropometry"},
        "s-anthropometry-form-schizophrenia":           {url:"$H/m/library/anthropometry-form.html",Table:"s-anthropometry-schizophrenia",task_name:"Anthropometry"},
        "s-ethnicity-data-schizophrenia":               {url:"$H/m/library/ethnicity-data.html",Table:"s-ethnicity-schizophrenia",form_module:"s-ethnicity-form-schizophrenia"},
        "s-ethnicity-form-schizophrenia":               {url:"$H/m/library/ethnicity-form.html",Table:"s-ethnicity-schizophrenia",task_name:"Ethnicity"},
        "s-lifestyle-data-schizophrenia":               {url:"$H/m/library/lifestyle-data.html",Table:"s-lifestyle-schizophrenia",form_module:"s-lifestyle-form-schizophrenia",task_name:"Lifestyle"},
        "s-lifestyle-form-schizophrenia":               {url:"$H/m/library/lifestyle-form.html",Table:"s-lifestyle-schizophrenia",task_name:"Lifestyle"},
        "s-education-data-schizophrenia":               {url:"$H/m/library/education-data.html",Table:"s-education-schizophrenia",form_module:"s-education-form-schizophrenia",task_name:"Education"},
        "s-education-form-schizophrenia":               {url:"$H/m/library/education-form.html",Table:"s-education-schizophrenia",task_name:"Education"},
        "s-concom-medication-data-schizophrenia":       {url:"$H/m/library/concom-medication-data.html",Table:"s-concom-medication-schizophrenia",form_module:"s-concom-medication-form-schizophrenia",task_name:"Unscheduled - Concomitant Medication"},
        "s-concom-medication-form-schizophrenia":       {url:"$H/m/library/concom-medication-form.html",Table:"s-concom-medication-schizophrenia",task_name:"Unscheduled - Concomitant Medication"},
        "s-concom-file-data-schizophrenia":		        {url:"$H/m/library/upload-file-data.html",Table:"s-concom-file-schizophrenia",form_module:"s-concom-file-form-schizophrenia",task_name:"Screening - Concomitant medication file upload"},
        "s-concom-file-form-schizophrenia":		        {url:"$H/m/library/upload-file-form.html",Table:"s-concom-file-schizophrenia",task_name:"Screening - Concomitant medication file upload"},
        "s-medical-history-data-schizophrenia":         {url:"$H/m/library/medical-history-data.html",Table:"s-medical-history-schizophrenia",form_module:"s-medical-history-form-schizophrenia"},
        "s-medical-history-form-schizophrenia":         {url:"$H/m/library/medical-history-form.html",Table:"s-medical-history-schizophrenia",task_name:"Medical History"},
        "s-ess-data-schizophrenia":                     {url:"$H/m/library/ess-data.html",Table:"s-ess-schizophrenia",form_module:"s-ess-form-schizophrenia"},
        "s-ess-form-schizophrenia":                     {url:"$H/m/library/ess-form.html",Table:"s-ess-schizophrenia",task_name:"Epworth Sleepiness Scale"},
        "s-isi-data-schizophrenia":                     {url:"$H/m/library/isi-data.html",Table:"s-isi-schizophrenia",form_module:"s-isi-form-schizophrenia"},
        "s-isi-form-schizophrenia":                     {url:"$H/m/library/isi-form.html",Table:"s-isi-schizophrenia",task_name:"Insomnia Severity Index"},
        "s-psqi-data-schizophrenia":                    {url:"$H/m/library/psqi-data.html",Table:"s-psqi-schizophrenia",form_module:"s-psqi-form-schizophrenia"},
        "s-psqi-form-schizophrenia":                    {url:"$H/m/library/psqi-form.html",Table:"s-psqi-schizophrenia",task_name:"Pittsburgh Sleep Quality Index (PSQI)"},
        "s-dass-data-schizophrenia":                    {url:"$H/m/library/dass-data.html",Table:"s-dass-schizophrenia",form_module:"s-dass-form-schizophrenia"},
        "s-dass-form-schizophrenia":                    {url:"$H/m/library/dass-form.html",Table:"s-dass-schizophrenia",task_name:"Depression Anxiety Stress Scale (DASS-21)"},

        "be-visit-date-data-schizophrenia":             {url:"$H/m/library/date-data.html",Table:"be-visit-date-schizophrenia",form_module:"be-visit-date-form-schizophrenia",task_name:"Visit Date"},
        "be-visit-date-form-schizophrenia":             {url:"$H/m/library/date-form.html",Table:"be-visit-date-schizophrenia",task_name:"Visit Date"},
        "be-pvt-data-schizophrenia":                    {url:"$H/m/library/pvt-data.html",Table:"be-pvt-schizophrenia",form_module:"be-pvt-form-schizophrenia",task_name:"PVT"},
        "be-pvt-form-schizophrenia":                    {url:"$H/m/library/pvt-form.html",Table:"be-pvt-schizophrenia",task_name:"PVT"},
        "be-pvt-pc-data-schizophrenia":                 {url:"$H/m/library/pvt-pc-data.html",Table:"be-pvt-pc-schizophrenia",form_module:"be-pvt-pc-form-schizophrenia",task_name:"PC PVT"},
        "be-pvt-pc-form-schizophrenia":                 {url:"$H/m/library/pvt-pc-form.html",Table:"be-pvt-pc-schizophrenia",task_name:"PC PVT"},

        "f-visit-date-data-schizophrenia":              {url:"$H/m/library/date-data.html",Table:"f-visit-date-schizophrenia",form_module:"f-visit-date-form-schizophrenia",task_name:"Visit Date"},
        "f-visit-date-form-schizophrenia":              {url:"$H/m/library/date-form.html",Table:"f-visit-date-schizophrenia",task_name:"Visit Date"},
        "f-anthropometry-data-schizophrenia":           {url:"$H/m/library/anthropometry-data.html",Table:"f-anthropometry-schizophrenia",form_module:"f-anthropometry-form-schizophrenia",task_name:"Anthropometry"},
        "f-anthropometry-form-schizophrenia":           {url:"$H/m/library/anthropometry-form.html",Table:"f-anthropometry-schizophrenia",task_name:"Anthropometry"},

        "serious-adverse-event-data-schizophrenia":   {url:"$H/m/library/serious-adverse-event-data.html",Table:"serious-adverse-event-schizophrenia",form_module:"serious-adverse-event-form-schizophrenia",task_name:"Serious Adverse EventOne"},
        "serious-adverse-event-form-schizophrenia":   {url:"$H/m/library/serious-adverse-event-form.html",Table:"serious-adverse-event-schizophrenia"},
        "serious-adverse-event-follow-up-data-schizophrenia":   {url:"$H/m/library/serious-adverse-event-follow-up-data.html",Table:"serious-adverse-event-follow-up-schizophrenia",form_module:"serious-adverse-event-follow-up-form-schizophrenia",task_name:"Serious Adverse Event Follow-up"},
        "serious-adverse-event-follow-up-form-schizophrenia":   {url:"$H/m/library/serious-adverse-event-follow-up-form.html",Table:"serious-adverse-event-follow-up-schizophrenia"},

        "gad7-data-schizophrenia":                    {url:"$H/m/library/gad7-data.html",Table:"gad7-schizophrenia",form_module:"gad7-form-schizophrenia"},
        "gad7-form-schizophrenia":                    {url:"$H/m/library/gad7-form.html",Table:"gad7-schizophrenia",task_name:"Generalised Anxiety Disorder (GAD-7)"},
        "fosq-data-schizophrenia":                    {url:"$H/m/library/fosq-data.html",Table:"fosq-schizophrenia",form_module:"fosq-form-schizophrenia"},
        "fosq-form-schizophrenia":                    {url:"$H/m/library/fosq-form.html",Table:"fosq-schizophrenia",task_name:"Funtional Outcomes of Sleep Questionnaire (FOSQ 10)"},
        "fosq30-data-schizophrenia":                  {url:"$H/m/library/fosq30-data.html",Table:"fosq30-schizophrenia",form_module:"fosq30-form-schizophrenia"},
        "fosq30-form-schizophrenia":                  {url:"$H/m/library/fosq30-form.html",Table:"fosq30-schizophrenia",task_name:"Funtional Outcomes of Sleep Questionnaire (FOSQ 30)"},
        "fss-data-schizophrenia":                     {url:"$H/m/library/fss-data.html",Table:"fss-schizophrenia",form_module:"fss-form-schizophrenia"},
        "fss-form-schizophrenia":                     {url:"$H/m/library/fss-form.html",Table:"fss-schizophrenia",task_name:"Fatigue Severity Scale"},
        "me-data-schizophrenia":                      {url:"$H/m/library/me-data.html",Table:"me-schizophrenia",form_module:"me-form-schizophrenia"},
        "me-form-schizophrenia":                      {url:"$H/m/library/me-form.html",Table:"me-schizophrenia",task_name:"Horne & Östberg Morningness-Eveningness Composite Questionnaire"},
        "map-data-schizophrenia":                     {url:"$H/m/library/map-data.html",Table:"map-schizophrenia",form_module:"map-form-schizophrenia"},
        "map-form-schizophrenia":                     {url:"$H/m/library/map-form.html",Table:"map-schizophrenia",task_name:"Multivariate Apnea Prediction Questionnaire"},
        "medications-data-schizophrenia":             {url:"$H/m/library/medications-data.html",Table:"medications-schizophrenia",form_module:"medications-form-schizophrenia"},
        "medications-form-schizophrenia":             {url:"$H/m/library/medications-form.html",Table:"medications-schizophrenia",task_name:"Medications"},
        "phq-data-schizophrenia":                     {url:"$H/m/library/phq-data.html",Table:"phq-schizophrenia",form_module:"phq-form-schizophrenia"},
        "phq-form-schizophrenia":                     {url:"$H/m/library/phq-form.html",Table:"phq-schizophrenia",task_name:"Patient Health Questionnaire (PHQ-9)"},
        "rec-drug-data-schizophrenia":                {url:"$H/m/library/rec-drug-data.html",Table:"rec-drug-schizophrenia",form_module:"rec-drug-form-schizophrenia"},
        "rec-drug-form-schizophrenia":                {url:"$H/m/library/rec-drug-form.html",Table:"rec-drug-schizophrenia",task_name:"Recreational Drugs"},
        "restless-leg-data-schizophrenia":            {url:"$H/m/library/restless-leg-data.html",Table:"restless-leg-schizophrenia",form_module:"restless-leg-form-schizophrenia"},
        "restless-leg-form-schizophrenia":            {url:"$H/m/library/restless-leg-form.html",Table:"restless-leg-schizophrenia",task_name:"Restless Legs"},
        "sds-data-schizophrenia":                     {url:"$H/m/library/sds-data.html",Table:"sds-schizophrenia",form_module:"sds-form-schizophrenia"},
        "sds-form-schizophrenia":                     {url:"$H/m/library/sds-form.html",Table:"sds-schizophrenia",task_name:"Sheehan Disability Scale"},
        "sdp-data-schizophrenia":                     {url:"$H/m/library/sdp-data.html",Table:"sdp-schizophrenia",form_module:"sdp-form-schizophrenia"},
        "sdp-form-schizophrenia":                     {url:"$H/m/library/sdp-form.html",Table:"sdp-schizophrenia",task_name:"Sleep Disorder Patterns"},
        "shi-data-schizophrenia":                     {url:"$H/m/library/shi-data.html",Table:"shi-schizophrenia",form_module:"shi-form-schizophrenia"},
        "shi-form-schizophrenia":                     {url:"$H/m/library/shi-form.html",Table:"shi-schizophrenia",task_name:"Sleep Hygiene Index (SHI)"},
        "dsst-data-schizophrenia":                    {url:"$H/m/neurocog/dsst-data.html",Table:"dsst-schizophrenia",form_module:"dsst-form-schizophrenia"},
        "dsst-form-schizophrenia":                    {url:"$H/m/neurocog/dsst-form.html",Table:"dsst-schizophrenia"},
        "finger-tapping6-after-data-schizophrenia":   {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"finger-tapping-schizophrenia",form_module:"finger-tapping6-after-form-schizophrenia"},
        "finger-tapping6-after-form-schizophrenia":   {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"finger-tapping-schizophrenia",Table2:"finger-tapping12-schizophrenia",task_name:"Finger Tapping - Morning"},
        "finger-tapping-alt-data-schizophrenia":      {url:"$H/m/neurocog/finger-tapping-data.html",Table:"finger-tapping-alt-schizophrenia",form_module:"finger-tapping-alt-form-schizophrenia"},
        "finger-tapping-alt-form-schizophrenia":      {url:"$H/m/neurocog/finger-tapping-alt-form.html",Table:"finger-tapping-alt-schizophrenia"},
        "finger-tapping12-before-data-schizophrenia": {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"finger-tapping12-schizophrenia",form_module:"finger-tapping12-before-form-schizophrenia"},
        "finger-tapping12-before-form-schizophrenia": {url:"$H/m/neurocog/finger-tapping12-before-form.html",Table:"finger-tapping12-schizophrenia",task_name:"Finger Tapping - Evening"},
        "finger-tapping12-alt-data-schizophrenia":    {url:"$H/m/neurocog/finger-tapping12-data.html",Table:"finger-tapping12-alt-schizophrenia",form_module:"finger-tapping12-alt-form-schizophrenia"},
        "finger-tapping12-alt-form-schizophrenia":    {url:"$H/m/neurocog/finger-tapping12-alt-form.html",Table:"finger-tapping12-alt-schizophrenia"},
        "letter-cancellation-data-schizophrenia":     {url:"$H/m/neurocog/letter-cancellation-data.html",Table:"letter-cancellation-schizophrenia",form_module:"letter-cancellation-form-schizophrenia"},
        "letter-cancellation-form-schizophrenia":     {url:"$H/m/neurocog/letter-cancellation-form.html",Table:"letter-cancellation-schizophrenia"},
        "nback1-data-schizophrenia":                  {url:"$H/m/neurocog/nback1-data.html",Table:"nback1-schizophrenia",form_module:"nback1-form-schizophrenia"},
        "nback1-form-schizophrenia":                  {url:"$H/m/neurocog/nback1-form.html",Table:"nback1-schizophrenia",task_name:"1-Back"},
        "nback2-data-schizophrenia":                  {url:"$H/m/neurocog/nback2-data.html",Table:"nback2-schizophrenia",form_module:"nback2-form-schizophrenia"},
        "nback2-form-schizophrenia":                  {url:"$H/m/neurocog/nback2-form.html",Table:"nback2-schizophrenia",task_name:"2-back"},
        "nback3-data-schizophrenia":                  {url:"$H/m/neurocog/nback3-data.html",Table:"nback3-schizophrenia",form_module:"nback3-form-schizophrenia"},
        "nback3-form-schizophrenia":                  {url:"$H/m/neurocog/nback3-form.html",Table:"nback3-schizophrenia",task_name:"3-Back"},
        "nback-upload-data-schizophrenia":            {url:"$H/m/neurocog/nback-upload-data.html",Table:"nback-upload-schizophrenia",form_module:"nback-upload-form-schizophrenia"},
        "nback-upload-form-schizophrenia":            {url:"$H/m/neurocog/nback-upload-form.html",Table:"nback-upload-schizophrenia",task_name:"N-Back Calculation Check"},
        "stroop-colour-data-schizophrenia":           {url:"$H/m/neurocog/stroop-colour-data.html",Table:"stroop-colour-schizophrenia",form_module:"stroop-colour-form-schizophrenia"},
        "stroop-colour-form-schizophrenia":           {url:"$H/m/neurocog/stroop-colour-form.html",Table:"stroop-colour-schizophrenia"},
        "stroop-text-data-schizophrenia":             {url:"$H/m/neurocog/stroop-text-data.html",Table:"stroop-text-schizophrenia",form_module:"stroop-text-form-schizophrenia"},
        "stroop-text-form-schizophrenia":             {url:"$H/m/neurocog/stroop-text-form.html",Table:"stroop-text-schizophrenia"},
        "tower-london-data-schizophrenia":            {url:"$H/m/neurocog/tower-london-data.html",Table:"tower-london-schizophrenia",form_module:"tower-london-form-schizophrenia"},
        "tower-london-form-schizophrenia":            {url:"$H/m/neurocog/tower-london-form.html",Table:"tower-london-schizophrenia"},
        "bpns-data-schizophrenia":                    {url:"$H/m/library/bpns-data.html",Table:"bpns-schizophrenia",form_module:"bpns-form-schizophrenia"},
        "bpns-form-schizophrenia":                    {url:"$H/m/library/bpns-form.html",Table:"bpns-schizophrenia",task_name:"Basic Psychological Need Satisfaction Scale"},
        "gses-data-schizophrenia":                    {url:"$H/m/library/gses-data.html",Table:"gses-schizophrenia",form_module:"gses-form-schizophrenia"},
        "gses-form-schizophrenia":                    {url:"$H/m/library/gses-form.html",Table:"gses-schizophrenia",task_name:"General Self-Efficacy Scale"},
        "hpq-data-schizophrenia":                     {url:"$H/m/library/hpq-data.html",Table:"hpq-schizophrenia",form_module:"hpq-form-schizophrenia"},
        "hpq-form-schizophrenia":                     {url:"$H/m/library/hpq-form.html",Table:"hpq-schizophrenia",task_name:"Health and Work Performance Questionnaire (HPQ)"},
        "poms-data-schizophrenia":                    {url:"$H/m/library/poms-data.html",Table:"poms-schizophrenia",form_module:"poms-form-schizophrenia"},
        "poms-form-schizophrenia":                    {url:"$H/m/library/poms-form.html",Table:"poms-schizophrenia",task_name:"Profile of Mood States Questionnaire (POMS)"},
        "kss-data-schizophrenia":                     {url:"$H/m/library/kss-data.html",Table:"kss-schizophrenia",form_module:"kss-form-schizophrenia"},
        "kss-form-schizophrenia":                     {url:"$H/m/library/kss-form.html",Table:"kss-schizophrenia",task_name:"Karolinska Sleepiness Scale (KSS)"},
        "medical-history-short-data-schizophrenia":   {url:"$H/m/library/medical-history-short-data.html",Table:"medical-history-short-schizophrenia",form_module:"medical-history-short-form-schizophrenia"},
        "medical-history-short-form-schizophrenia":   {url:"$H/m/library/medical-history-short-form.html",Table:"medical-history-short-schizophrenia",task_name:"Medical History Short"},
        "sleep-history-data-schizophrenia":           {url:"$H/m/library/sleep-history-data.html",Table:"sleep-history-schizophrenia",form_module:"sleep-history-form-schizophrenia"},
        "sleep-history-form-schizophrenia":           {url:"$H/m/library/sleep-history-form.html",Table:"sleep-history-schizophrenia",task_name:"Sleep History"},
        "ffs-data-schizophrenia":                     {url:"$H/m/library/ffs-data.html",Table:"ffs-schizophrenia",form_module:"ffs-form-schizophrenia"},
        "ffs-form-schizophrenia":                     {url:"$H/m/library/ffs-form.html",Table:"ffs-schizophrenia",task_name:"Flinders Fatigue Scale"},
        "actiwatch-data-schizophrenia":               {url:"$H/m/library/actiwatch-data.html",Table:"actiwatch-schizophrenia",form_module:"actiwatch-form-schizophrenia"},
        "actiwatch-form-schizophrenia":               {url:"$H/m/library/actiwatch-form.html",Table:"actiwatch-schizophrenia"},
        "eq-5d-data-schizophrenia":                   {url:"$H/m/library/eq-5d-data.html",Table:"eq-5d-schizophrenia",form_module:"eq-5d-form-schizophrenia"},
        "eq-5d-form-schizophrenia":                   {url:"$H/m/library/eq-5d-form.html",Table:"eq-5d-schizophrenia",task_name:"EQ-5D-5L instrument"},
        "sf36-data-schizophrenia":                    {url:"$H/m/library/sf36-data.html",Table:"sf36-schizophrenia",form_module:"sf36-form-schizophrenia"},
        "sf36-form-schizophrenia":                    {url:"$H/m/library/sf36-form.html",Table:"sf36-schizophrenia",task_name:"Short Form Survey Instrument (SF36)"},
        "iwqlq-data-schizophrenia":                   {url:"$H/m/library/iwqlq-data.html",Table:"iwqlq-schizophrenia",form_module:"iwqlq-form-schizophrenia"},
        "iwqlq-form-schizophrenia":                   {url:"$H/m/library/iwqlq-form.html",Table:"iwqlq-schizophrenia",task_name:"Impact of Weight on Quality of Life Questionnaire (IWQLQ)"},
        "brief-illness-perception-questionnaire-data-schizophrenia":   {url:"$H/m/library/brief-illness-perception-questionnaire-data.html",Table:"brief-illness-perception-questionnaire-schizophrenia",form_module:"brief-illness-perception-questionnaire-form-schizophrenia"},
        "brief-illness-perception-questionnaire-form-schizophrenia":   {url:"$H/m/library/brief-illness-perception-questionnaire-form.html",Table:"brief-illness-perception-questionnaire-schizophrenia",task_name:"Brief Illness Perception Questionnaire"},
        "breif-sexual-function-inventory-data-schizophrenia":   {url:"$H/m/library/breif-sexual-function-inventory-data.html",Table:"breif-sexual-function-inventory-schizophrenia",form_module:"breif-sexual-function-inventory-form-schizophrenia"},
        "breif-sexual-function-inventory-form-schizophrenia":   {url:"$H/m/library/breif-sexual-function-inventory-form.html",Table:"breif-sexual-function-inventory-schizophrenia",task_name:"Brief Sexual Function Inventory"},
        "female-sexual-function-index-data-schizophrenia":   {url:"$H/m/library/female-sexual-function-index-data.html",Table:"female-sexual-function-index-schizophrenia",form_module:"female-sexual-function-index-form-schizophrenia"},
        "female-sexual-function-index-form-schizophrenia":   {url:"$H/m/library/female-sexual-function-index-form.html",Table:"female-sexual-function-index-schizophrenia",task_name:"Female Sexual Function Index (FSFI)"},
        "three-factor-eating-questionnaire-data-schizophrenia":   {url:"$H/m/library/three-factor-eating-questionnaire-data.html",Table:"three-factor-eating-questionnaire-schizophrenia",form_module:"three-factor-eating-questionnaire-form-schizophrenia"},
        "three-factor-eating-questionnaire-form-schizophrenia":   {url:"$H/m/library/three-factor-eating-questionnaire-form.html",Table:"three-factor-eating-questionnaire-schizophrenia",task_name:"Three-Factor Eating Questionnaire (TFEQ-R18)"},
        "glasgow-content-of-thoughts-inventory-data-schizophrenia":   {url:"$H/m/library/glasgow-content-of-thoughts-inventory-data.html",Table:"glasgow-content-of-thoughts-inventory-schizophrenia",form_module:"glasgow-content-of-thoughts-inventory-form-schizophrenia"},
        "glasgow-content-of-thoughts-inventory-form-schizophrenia":   {url:"$H/m/library/glasgow-content-of-thoughts-inventory-form.html",Table:"glasgow-content-of-thoughts-inventory-schizophrenia",task_name:"Glasgow Content of Thoughts Inventory"},
        "glasgow-sleep-effort-scale-data-schizophrenia":   {url:"$H/m/library/glasgow-sleep-effort-scale-data.html",Table:"glasgow-sleep-effort-scale-schizophrenia",form_module:"glasgow-sleep-effort-scale-form-schizophrenia"},
        "glasgow-sleep-effort-scale-form-schizophrenia":   {url:"$H/m/library/glasgow-sleep-effort-scale-form.html",Table:"glasgow-sleep-effort-scale-schizophrenia",task_name:"Glasgow Sleep Effort Scale"},
        "pre-sleep-arousal-scale-data-schizophrenia":   {url:"$H/m/library/pre-sleep-arousal-scale-data.html",Table:"pre-sleep-arousal-scale-schizophrenia",form_module:"pre-sleep-arousal-scale-form-schizophrenia"},
        "pre-sleep-arousal-scale-form-schizophrenia":   {url:"$H/m/library/pre-sleep-arousal-scale-form.html",Table:"pre-sleep-arousal-scale-schizophrenia",task_name:"Pre-Sleep Arousal Scale"},
        "stanford-sleepiness-scale-data-schizophrenia":   {url:"$H/m/library/stanford-sleepiness-scale-data.html",Table:"stanford-sleepiness-scale-schizophrenia",form_module:"stanford-sleepiness-scale-form-schizophrenia"},
        "stanford-sleepiness-scale-form-schizophrenia":   {url:"$H/m/library/stanford-sleepiness-scale-form.html",Table:"stanford-sleepiness-scale-schizophrenia",task_name:"Stanford Sleepiness Scale"},
        "dbas-16-data-schizophrenia":                 {url:"$H/m/library/dbas-16-data.html",Table:"dbas-16-schizophrenia",form_module:"dbas-16-form-schizophrenia"},
        "dbas-16-form-schizophrenia":                 {url:"$H/m/library/dbas-16-form.html",Table:"dbas-16-schizophrenia",task_name:"Dysfunctional Beliefs and Attitudes about Sleep (DBAS-16)"},
        "multidimensional-fatigue-symptom-inventory-data-schizophrenia":   {url:"$H/m/library/multidimensional-fatigue-symptom-inventory-data.html",Table:"multidimensional-fatigue-symptom-inventory-schizophrenia",form_module:"multidimensional-fatigue-symptom-inventory-form-schizophrenia"},
        "multidimensional-fatigue-symptom-inventory-form-schizophrenia":   {url:"$H/m/library/multidimensional-fatigue-symptom-inventory-form.html",Table:"multidimensional-fatigue-symptom-inventory-schizophrenia",task_name:"Multidimensional Fatigue Symptom Inventory"},
        "fatigue-symptom-inventory-data-schizophrenia":   {url:"$H/m/library/fatigue-symptom-inventory-data.html",Table:"fatigue-symptom-inventory-schizophrenia",form_module:"fatigue-symptom-inventory-form-schizophrenia"},
        "fatigue-symptom-inventory-form-schizophrenia":   {url:"$H/m/library/fatigue-symptom-inventory-form.html",Table:"fatigue-symptom-inventory-schizophrenia",task_name:"Fatigue Symptom Inventory"},
        "hads-data-schizophrenia":                    {url:"$H/m/library/hads-data.html",Table:"hads-schizophrenia",form_module:"hads-form-schizophrenia"},
        "hads-form-schizophrenia":                    {url:"$H/m/library/hads-form.html",Table:"hads-schizophrenia",task_name:"Hospital Anxiety and Depression Scale (HADS)"},
        "pvt-data-schizophrenia":                     {url:"$H/m/library/pvt-data.html",Table:"pvt-schizophrenia",form_module:"pvt-form-schizophrenia"},
        "pvt-form-schizophrenia":                     {url:"$H/m/library/pvt-form.html",Table:"pvt-schizophrenia"},
        "pvt-pc-data-schizophrenia":                     {url:"$H/m/library/pvt-pc-data.html",Table:"pvt-pc-schizophrenia",form_module:"pvt-pc-form-schizophrenia"},
        "pvt-pc-form-schizophrenia":                     {url:"$H/m/library/pvt-pc-form.html",Table:"pvt-pc-schizophrenia"},
        "stop-bang-data-schizophrenia":               {url:"$H/m/library/stop-bang-data.html",Table:"stop-bang-schizophrenia",form_module:"stop-bang-form-schizophrenia"},
        "stop-bang-form-schizophrenia":               {url:"$H/m/library/stop-bang-form.html",Table:"stop-bang-schizophrenia",task_name:"Stop-Bang"},
        "gds-data-schizophrenia":                     {url:"$H/m/library/gds-data.html",Table:"gds-schizophrenia",form_module:"gds-form-schizophrenia"},
        "gds-form-schizophrenia":                     {url:"$H/m/library/gds-form.html",Table:"gds-schizophrenia",task_name:"Geriatric Depression Scale"},
        "ispq-data-schizophrenia":                    {url:"$H/m/library/ispq-data.html",Table:"ispq-schizophrenia",form_module:"ispq-form-schizophrenia"},
        "ispq-form-schizophrenia":                    {url:"$H/m/library/ispq-form.html",Table:"ispq-schizophrenia",task_name:"Impact to Sleep and Preferences Questionnaire"},
        "tipi-data-schizophrenia":                    {url:"$H/m/library/tipi-data.html",Table:"tipi-schizophrenia",form_module:"tipi-form-schizophrenia"},
        "tipi-form-schizophrenia":                    {url:"$H/m/library/tipi-form.html",Table:"tipi-schizophrenia",task_name:"Ten-Item Personality Inventory (TIPI)"},
        "pvt-cal-data-schizophrenia":                    {url:"$H/m/library/pvt-cal-data.html",Table:"pvt-cal-schizophrenia",form_module:"pvt-cal-form-schizophrenia"},
        "pvt-cal-form-schizophrenia":                    {url:"$H/m/library/pvt-cal-form.html",Table:"pvt-cal-schizophrenia"},
    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.hosting_path=$vm.hosting_path.replace('online-questionnaire','')
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
//    if(window.location.toString().indexOf('tb=demo')!=-1){
        for(p in $vm.module_list){
            $vm.module_list[p].Table="demo-"+$vm.module_list[p].Table;
        }
//    }
})();
